name: Objektorienterad programmering och modellering

description: DA361A

github: https://github.com/Tibbelit/ia-oop-python

analytics: UA-48530327-3

url: http://mah-webb.github.io

# highlighter: pygments
# markdown: kramdown

kramdown:
    input: GFM

exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'LICENSE.txt', 'vendor']

include: ['.htaccess']

gems: [jekyll-paginate]

permalink: /blog/:categories/:title.html

paginate: 5
paginate_path: /blog/page:num
